site_name: Anno Modloader Reference
site_url: https://jakobharder.github.io/anno-mod-loader

plugins:
  - search
  - macros

nav:
  - Overview: index.md
  #- "Changes in 117":
  - Important Changes: changes-117.md
  - New Features: new-features-117.md
  - Create Mods:
    - Modinfo: modinfo.md
    - Structure:
      - Loading Order: structure/loading-order.md
      - Sub-Mods: structure/submods.md
      - Zip Files: structure/zipfiles.md
      - Links: structure/links.md
    - ModOps:
      - modops/index.md
      - Basic Types: modops/basics.md
      - Grouping: modops/grouping.md
      - Conditions: modops/conditions.md
      - Dynamic Content: modops/content.md
      - Item Lists: modops/lists.md
      - Examples: modops/examples.md
    - Options: options.md
    - InfoTips: infotips.md
    - "CFG, FC Patches": cfg-fc-patches.md
  - Use Mods:
    - Mod Profiles: profiles.md
  - External:
    - XPath Cheat Sheet: https://devhints.io/xpath

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - header.autohide
    - navigation.indexes
    # - navigation.tabs

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys

extra_css:
  - stylesheets/extra.css

extra:
    all: '<span class="version-tag" title="Available in all supported Annos">:material-animation-outline: 117 & 1800</span>'
    a1800: '<span class="version-tag" title="Only available in Anno 1800">:material-factory: 1800</span>'
    a117: '<span class="version-tag" title="Only available in Anno 117">:material-pillar: 117</span>'