site_name: Anno Modloader Reference
site_url: https://jakobharder.github.io/anno-mod-loader

plugins:
  - search

nav:
  - Overview: index.md
  #- "Changes in 117":
  - Important Changes: changes-117.md
  - New Features: new-features-117.md
  - Features:
    - ModOps:
      - modops/index.md
      - Basic Types: modops/basics.md
      - Merge: modops/merge.md
      - Grouping: modops/grouping.md
      - Conditions: modops/conditions.md
      - Content: modops/content.md
      - Examples: modops/examples.md
    - Modinfo: modinfo.md
    - Loading Order: loading-order.md
    - Sub-Mods: submods.md
    - Options: options.md
    - InfoTips: infotips.md
  - XPath:
    - Cheat Sheet: https://devhints.io/xpath

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - content.code.copy
    - navigation.footer
    - header.autohide
    - navigation.indexes
    # - navigation.tabs

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys