name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Build
        run: |
          bazel build //... -c opt

      - name: Test
        run: bazel test //tests/xml:xml-tests -c opt

      - name: Package
        run: |
          BIN_DIR=$(bazel info bazel-bin -c opt)

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            $BIN_DIR/cmd/xmltest/xmltest2.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Build
        run: |
          bazel --noworkspace_rc --bazelrc=.linux.bazelrc build //cmd/... //tests/... -c opt

      - name: Test
        run: bazel --noworkspace_rc --bazelrc=.linux.bazelrc test //tests/xml:xml-tests -c opt
